### ISSUE TITLE
What is the lua script used for?

### ISSUE THREAD

**Issue by GeneZC** [LuiCat/Nogoer#1]
And the lua.a has not been included in the repo

**Comment by LuiCat** [comment]
The Lua script is used to automate the matches. Useful for collecting data. We didn't included a lua.a file in source code, so that you have to compile it yourself. Sorry for this inconvenience.

**Comment by GeneZC** [comment]
So how can I use the lua script, or should write one by myself ?

**Comment by LuiCat** [comment]
Nope or yep. That's a undocumented feature for private uses. I'm not remembering how it works now, so please perhaps refer to the source code for available Lua functions.

Seems that I have two Lua functions (loadEngine, start) registered. The two Lua functions should be plain-forward to use. Take care that they would block the calling lua thread until loading or the game is finished.

For reference of function behaviors, the exact position where Lua functions are registered is in constructor ChessScript::ChessScript. The parameters is controlled in registered C functions lua_XXXXX, with each Lua's stack operations corresponding to each parameter or returned values.

**Comment by GeneZC** [comment]
That's reasonable. Thanks a lot!
